apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: Microsoft
  name: win2k19-install-iso
  namespace: kubevirt-gitops
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 6Gi
    volumeMode: Filesystem
  source:
    s3:
      url: https://kubevirt-demo-win.s3.eu-west-1.amazonaws.com/win2k19.iso
      secretRef: kubevirt-demo-win

